spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tHgzE3a4mT7vsGUpjDt
      secret-key: xgsFxxytT8anhPW4n5rOW8CLlCHIoo
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  application:
    name: gulimall-product


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #开启主键自增
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000
logging:
  level:
    com.atguigu.gulimall: debug


#alibaba.cloud.access-key=your-ak
#alibaba.cloud.secret-key=your-sk
#alibaba.cloud.oss.endpoint=***