spring:
  cloud:
    alicloud:
      access-key: LTAI5tHgzE3a4mT7vsGUpjDt
      secret-key: xgsFxxytT8anhPW4n5rOW8CLlCHIoo
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-liuyongjian
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000

