spring:
  cloud:
    alicloud:
      access-key: LTAI5t9hVmctmENxoU7VX8Qq
      secret-key: mCN5KWqBAuAM1t4j8snauueZdWusiF
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-liuyongjian
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000

